# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Brand.create(name:"Apothic", country:"United States", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/United-States.png", img: "https://wikiliq.org/wp-content/uploads/2021/02/Apothic-wines-min.jpg", description:"Apothic Wines is a range of wines produced by California's largest wine exporter, E.J. Gallo. It began with a single wine, the Apothic Red, which was first released in commercial volumes in 2010. The wine is a blend of Zinfandel, Merlot, Syrah and Cabernet Sauvignon, made in a full-bodied style with ripe, fruit-forward characters and some residual sugar.", website:"https://www.apothic.com/")
# Brand.create(name:"Kendall-Jackson", country:"United States", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/United-States.png", img: "https://wikiliq.org/wp-content/uploads/2021/02/Kendall-Jackson-wine-min.jpg", description:"Kendall-Jackson Vineyard Estates is a vineyard and winery, under the Kendall-Jackson brand, located in Santa Rosa, California in the Sonoma Valley wine country. As of 2010 Kendall-Jackson was the highest-selling brand of SUPER-PREMIUM wine (retailing for more than US$15 per bottle) in the United States.", website:"https://www.kj.com/")
Brand.create(name:"Captian Morgan", country:"Canada", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/Canada.png", img: "https://wikiliq.org/wp-content/uploads/2021/02/Captain-Morgan.jpg", description:"Captain Morgan is a brand of flavored rums produced by British alcohol conglomerate Diageo. It is named after the 17th-century Welsh privateer of the Caribbean, Sir Henry Morgan. Since 2017, the label has used the slogan 'Live like the Captain'.", website:"https://www.captainmorgan.com/")
Brand.create(name:"Bacardi Rum", country:"Cuba", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/Cuba.png", img: "https://wikiliq.org/wp-content/uploads/2021/02/Bacardi.jpg", description:"Bacardi Limited is one of the largest privately held, family-owned spirits companies in the world. Originally known for its eponymous Bacardi white rum, it now has a portfolio of more than 200 brands and labels. Founded in Cuba in 1862 and family-owned for seven generations, Bacardi Limited employs more than 7,000 people with sales in approximately 170 countries. Bacardi Limited refers to the Bacardi group of companies, including Bacardi International Limited.", website:"https://www.bacardi.com/")
Brand.create(name:"Jack Daniel's", country:"United States", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/United-States.png", img:"https://wikiliq.org/wp-content/uploads/2021/02/Jack-Daniels.jpg", description:"Jack Daniel's is a brand of Tennessee whiskey. It is produced in Lynchburg, Tennessee, by the Jack Daniel Distillery, which has been owned by the Brown Forman Corporation since 1956.", website:"https://www.jackdaniels.com/")
Brand.create(name:"Smirnoff Vodka", country:"United States", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/United-States.png",img:"https://wikiliq.org/wp-content/uploads/2021/02/Smirnoff.jpg", description:"Smirnoff is a brand of vodka owned and produced by the British company Diageo. The Smirnoff brand began with a vodka distillery founded in Moscow by Pyotr Arsenievich Smirnov", website:"https://www.smirnoff.com/")
Brand.create(name:"Bud Light", country:"United States", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/United-States.png",img:"https://wikiliq.org/wp-content/uploads/2021/02/Bud-Light-Beer.jpg", description:"Discover the Ultimate List of Wineries, Breweries, Spirits, Whiskey, and other Producers of Alcoholic Beverages. Browse from thousands of new, local, and well-known brands. Explore reviews, ratings, and facts about wine, beer, and spirits. Choose from hundreds of thousands of brands and find all your favorite spirits from around the world. WikiliQ ideal for anyone looking to get their hands on specific bottles of wine, beer, or liquor. Enjoy the best spirits from around the world.", website:"https://www.budlight.com/")
Brand.create(name:"Samuel Adams", country:"United States", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/United-States.png",img:"https://wikiliq.org/wp-content/uploads/2021/02/Samuel-Adams.jpg", description:"Samuel Adams is the flagship brand of the Boston Beer Company. The brand name was chosen in honor of Founding Father of the United States Samuel Adams. Adams inherited his father's brewery on King Street. Some historians say he was a brewer, while others describe him as a maltster.", website:"https://www.samueladams.com/")
Brand.create(name:"Blue Moon Beer", country:"United States", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/United-States.png",img:"https://wikiliq.org/wp-content/uploads/2021/05/Blue-Moon-Beer.jpg", description:"Blue Moon Belgian White is a Belgian-style witbier brewed by MillerCoors under the name the Blue Moon Brewing Co. It was launched in 1995, and was originally brewed in Golden, Colorado", website:"https://www.bluemoonbrewingcompany.com/")
Brand.create(name:"Corona", country:"Mexico", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/Mexico.png",img:"https://wikiliq.org/wp-content/uploads/2021/02/Corona-Beer.jpg", description:"Corona is a brand of beer produced by Mexican brewery Cervecería Modelo and owned by Belgian company AB InBev. It is the top-selling brand of imported beer in the United States. It is often served with a wedge of lime or lemon in the neck of the bottle to add tartness and flavor.", website:"https://www.coronausa.com/")
Brand.create(name:"Hennessy", country:"France", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/France.png",img:"https://wikiliq.org/wp-content/uploads/2021/02/Hennessy.jpg", description:"as Hennessy & Co., commonly known simply as Hennessy, is a French cognac distiller with its headquarters located in Cognac, France. Jas Hennessy & Co. sells about 50 million bottles a year worldwide, making it the largest cognac producer, supplying more than 40% of the world's cognac, a variety of brandy.", website:"http://hennessy.com/")
Brand.create(name:"Gallo Estate", country:"United States", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/United-States.png",img:"https://wikiliq.org/wp-content/uploads/2021/02/Gallo-wines-min.jpg", description:"Gallo Estate Cabernet Sauvignon blends the finest Cabernet lots from our Sonoma County vineyards. The nose is decadent, evocative of ripe wild blackberries, juicy blueberries and mocha. On the impressively dense palate, concentrated notes of black currant and blackberry jam are joined by classic notes of tobacco, dark chocolate, allspice and cedar before a long, lingering finish.", website:"https://www.gallo.com/")
Brand.create(name:"Jameson Irish Whiskey", country:"Ireland", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/Ireland.png",img:"https://wikiliq.org/wp-content/uploads/2021/02/Jameson.jpg", description:"Jameson is a blended Irish whiskey produced by the Irish Distillers subsidiary of Pernod Ricard. Originally one of the six main Dublin Whiskeys at the Jameson Distillery Bow St., Jameson is now distilled at the New Midleton Distillery in County Cork.", website:"http://jamesonwhiskey.com/")
Brand.create(name:"Jim Beam", country:"United States", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/United-States.png",img:"https://wikiliq.org/wp-content/uploads/2021/02/Jim-Beam.jpg", description:"Jim Beam is an American brand of bourbon whiskey produced in Clermont, Kentucky, by Beam Suntory. It is one of the best-selling brands of bourbon in the world. Since 1795, seven generations of the Beam family have been involved in whiskey production for the company that produces the brand.", website:"https://www.jimbeam.com/en/")
Brand.create(name:"Decoy Wines", country:"United State", country_img: "https://wikiliq.org/wp-content/uploads/2021/02/United-States.png",img:"https://wikiliq.org/wp-content/uploads/2021/05/Decoy-Wines.jpg", description:"About Decoy. Our Brut Cuvée is crafted in the méthode champenoise tradition to ensure that your special moments truly sparkle, so pop a bottle open and enjoy all your speical occations with Decoy. Our Decoy Limited is now available for you to experience featuring a Cabernet, Red Blend and Pinot Noir. Crafted using grapes from some of the most acclaimed Napa Valley and Sonoma Coast vineyards, including our own estate properties, these wines showcase the pinnacle of Decoy winemaking.", website:"https://www.decoywines.com/")

puts("Seeding is completed....")